/**
 * Brief Mode — 参考 FanBox "Brief" 模式
 * 结构化简报文件, agent 先读再执行
 * 用户确认后 agent 才开始工作
 */

// ══════════════════════════════════════════════
// Types
// ══════════════════════════════════════════════

export interface BriefSection {
  /** Section title */
  title: string;
  /** Section content (markdown) */
  content: string;
  /** Section type for formatting */
  type: 'context' | 'task' | 'constraints' | 'preferences' | 'history' | 'custom';
}

export interface AgentBrief {
  /** Brief ID */
  id: string;
  /** Brief title */
  title: string;
  /** Agent ID this brief is for */
  agentId: string;
  /** Workspace path */
  workspacePath: string;
  /** Brief sections */
  sections: BriefSection[];
  /** When the brief was created */
  createdAt: number;
  /** Whether the agent has acknowledged the brief */
  acknowledged: boolean;
}

// ══════════════════════════════════════════════
// Brief Mode Manager
// ══════════════════════════════════════════════

const BRIEF_DIR_NAME = '.yuai-briefs';

export class BriefModeManager {
  /** Generate a brief from context */
  generateBrief(
    agentId: string,
    workspacePath: string,
    task: string,
    context?: {
      recentFiles?: string[];
      preferences?: string[];
      constraints?: string[];
      history?: string[];
    }
  ): AgentBrief {
    const sections: BriefSection[] = [];

    // Task section
    sections.push({
      title: '任务',
      content: task,
      type: 'task',
    });

    // Context section
    if (context?.recentFiles?.length) {
      sections.push({
        title: '相关文件',
        content: context.recentFiles.map(f => `- ${f}`).join('\n'),
        type: 'context',
      });
    }

    // Constraints section
    if (context?.constraints?.length) {
      sections.push({
        title: '约束条件',
        content: context.constraints.map(c => `- ${c}`).join('\n'),
        type: 'constraints',
      });
    }

    // Preferences section
    if (context?.preferences?.length) {
      sections.push({
        title: '偏好设置',
        content: context.preferences.map(p => `- ${p}`).join('\n'),
        type: 'preferences',
      });
    }

    // History section
    if (context?.history?.length) {
      sections.push({
        title: '历史上下文',
        content: context.history.join('\n'),
        type: 'history',
      });
    }

    return {
      id: `brief-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      title: `Brief: ${task.slice(0, 50)}`,
      agentId,
      workspacePath,
      sections,
      createdAt: Date.now(),
      acknowledged: false,
    };
  }

  /** Serialize a brief to markdown */
  serializeBrief(brief: AgentBrief): string {
    const lines: string[] = [];

    lines.push(`# ${brief.title}`);
    lines.push('');
    lines.push(`> Agent: ${brief.agentId} | Workspace: ${brief.workspacePath}`);
    lines.push('');

    for (const section of brief.sections) {
      lines.push(`## ${section.title}`);
      lines.push('');
      lines.push(section.content);
      lines.push('');
    }

    lines.push('---');
    lines.push('*Generated by yuai Brief Mode*');

    return lines.join('\n');
  }

  /** Write a brief to the workspace */
  async writeBrief(brief: AgentBrief): Promise<string> {
    const { join } = await import('@tauri-apps/api/path');
    const { writeTextFile, mkdir, exists } = await import('@tauri-apps/plugin-fs');

    const briefDir = await join(brief.workspacePath, BRIEF_DIR_NAME);
    if (!(await exists(briefDir))) {
      await mkdir(briefDir, { recursive: true });
    }

    const briefPath = await join(briefDir, `${brief.id}.md`);
    await writeTextFile(briefPath, this.serializeBrief(brief));

    return briefPath;
  }

  /** Generate the agent prompt that references the brief */
  generateAgentPrompt(briefPath: string): string {
    return [
      `请先阅读以下简报文件，了解任务背景和约束条件：`,
      `@${briefPath}`,
      ``,
      `阅读完成后，请确认你已理解任务，然后开始执行。`,
    ].join('\n');
  }

  /** Mark a brief as acknowledged */
  acknowledgeBrief(brief: AgentBrief): AgentBrief {
    return { ...brief, acknowledged: true };
  }

  /** Parse a brief from markdown */
  parseBrief(content: string): Partial<AgentBrief> {
    const lines = content.split('\n');
    const sections: BriefSection[] = [];
    let currentSection: BriefSection | null = null;

    for (const line of lines) {
      if (line.startsWith('# ') && !line.startsWith('## ')) {
        // Title
        continue;
      }
      if (line.startsWith('## ')) {
        if (currentSection) sections.push(currentSection);
        currentSection = {
          title: line.slice(3).trim(),
          content: '',
          type: 'custom',
        };
        continue;
      }
      if (currentSection) {
        currentSection.content += line + '\n';
      }
    }
    if (currentSection) sections.push(currentSection);

    return { sections };
  }
}

// Singleton
export const globalBriefMode = new BriefModeManager();
